### PR TITLE
added ttf folder and files

### PR DESCRIPTION
**Pull request by BenRoe**
I converted the .bdf files (not powerline) with the tool called [Bits'N'Picas](https://github.com/kreativekorp/bitsnpicas).
The powerline files are not rendering on mac.

### CODE REVIEW

**Comment by BenRoe** [comment]
Fix #7

**Comment by sunaku** [comment]
Thanks for this PR :+1: I'll try it out soon. :sweat_smile: 

Could you share the commands used to generate this font?  We need to automate the TTF generation as part of the Rakefile build script, as opposed to just checking in precompiled TTF into the repository. :nerd_face:

**Comment by sunaku** [comment]
Hmm, it seems all of the generated TTF fonts have the same name.  I'm currently unable to run Bits'n'Picas because Oracle JRE is not available for my [*musl*-based](https://voidlinux.org/) Linux.  It'll take more time for me to switch to *glibc*.

**Comment by sunaku** [comment]
I'll just merge this PR for now and deal with automation later. :sweat_smile: Thanks for your contribution!

**Pull request merged**
